spring.datasource.url=jdbc:postgresql://localhost:5432/budgetDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=yasBudgetUser
spring.datasource.password=budgetpwd

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true