### For Documentation: https://github.com/actions : Org => actions ###
### For Documentation: https://github.com/azure : Org => azure ###
### For Documentation: https://github.com/hashicorp : Org => hashicorp ###

name: Deploy App Java with Maven

on:
  workflow_call: ### pipeline.yml will call it ###
  workflow_dispatch: ### Manual Triggering ###

permissions:
    id-token: write
    packages: read
    contents: read

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Azure OIDC login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Configure SSH key on the Github Runner
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/stouchi_vm
            chmod 600 ~/.ssh/stouchi_vm
      
      - name: Derive SSH public key from private key before terraform init
        run: ssh-keygen -y -f ~/.ssh/stouchi_vm > ~/.ssh/stouchi_vm.pub

      - name: Set up Terraform ### We still need to run Terraform in deploy-job to get VM_IP ###
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init ### Github Runner connects to remote state thanks to backend.tf ###
        working-directory: terraform/azure
        run: terraform init
      
      - name: Start VM
        run: |
          az vm start \
            --resource-group stouchi-resources \
            --name stouchi-machine

      - name: Get VM public IP
        working-directory: terraform/azure
        run: |
          VM_IP=$(terraform output -raw vm_public_ip)
          echo "VM_IP=$VM_IP" >> "$GITHUB_ENV"
        
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      
      - name: Wait for SSH connection
        run: |
          for i in {1..12}; do
            if ssh \
              -i ~/.ssh/stouchi_vm \
              -o StrictHostKeyChecking=no \
              -o ConnectTimeout=10 \
              deploy@$VM_IP \
              "echo SSH connection successful"; then
              exit 0
            fi

            echo "SSH not ready yet. Retrying in 10 seconds..."
            sleep 10
          done

          echo "SSH connection could not be established."
          exit 1

      - name: Copy Ansible Vault password to temporary file
        run: |
          printf '%s' "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/stouchi_vault_pwd
          chmod 600 /tmp/stouchi_vault_pwd

      - name: Run Ansible playbook
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventory.yml \
            -l stouchi-prod-server \
            -e "ansible_host=$VM_IP" \
            --vault-password-file /tmp/stouchi_vault_pwd \
            playbook.yml

      - name: Test port 8080
        run: |
          timeout 5 bash -c "</dev/tcp/$VM_IP/8080" \
            && echo "Port 8080 is reachable" \
            || echo "Port 8080 is NOT reachable"
      
      - name: Health Check
        run: |
          for i in {1..12}; do
            echo "Health Check Attempt $i/12"

            liveness=$(curl -s --fail "http://${VM_IP}:8080/actuator/health/liveness")
            readiness=$(curl -s --fail "http://${VM_IP}:8080/actuator/health/readiness")

            echo "Liveness:  $liveness"
            echo "Readiness: $readiness"

            if [[ "$liveness" == '{"status":"UP"}' && "$readiness" == '{"status":"UP"}' ]]; then
              echo "Application is healthy!"
              exit 0
            fi

            echo "Application not ready yet. Waiting 5 seconds..."
            sleep 5
          done

          echo "Application failed the health check."
          exit 1