name: Java with Maven

on:
  push:
    branches:  [main]
  pull_request:
    branches:  [main]

permissions:
  contents: read
  packages: write

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 17 and cache Maven
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run tests
        run:  mvn test 

  build-push:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/stouchi-app

      - name: Build and push Docker image to GHCRegistry
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  
  deploy:

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: build-push

    runs-on: ubuntu-latest

    steps: 

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: deploy
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/stouchi
            docker compose pull 
            docker compose up -d

