name: Java with Maven

on:
  push:
    branches:  [main]
  pull_request:
    branches:  [main]

permissions:
  contents: read
  packages: write

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 17 and cache Maven
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run tests
        run:  mvn test 

  build-push:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/stouchi-app

      - name: Build and push Docker image to GHCRegistry
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  
  deploy:

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: build-push

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Azure OIDC login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init ### Github Runner connects to remote state thanks to backend.tf ###
        working-directory: terraform/azure
        run: terraform init

      - name: Terraform plan
        working-directory: terraform/azure
        run: terraform plan

      - name: Terraform apply
        working-directory: terraform/azure
        run: terraform apply -auto-approve

      - name: Get VM public IP
        working-directory: terraform/azure
        run: |
          VM_IP=$(terraform output -raw vm_public_ip)
          echo "VM_IP=$VM_IP" >> "$GITHUB_ENV"
        
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      
      - name: Configure SSH key on the Github Runner
        run: |
            mkdir ~/.ssh
            echo "${{ secrets.SERVER_SSH_KEY}} " > ~/.ssh/stouch_vm
            chmod 600 ~/.ssh/stouchi_vm
      
      - name: Test SSH connection
        run: |
          ssh \
            -i ~/.ssh/stouchi_vm \
            -o StrictHostKeyChecking=no \
            deploy@$VM_IP \
            "echo SSH connection successful"

            - name: Copy Ansible Vault password to temporary file
        run: |
          printf '%s' "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /tmp/stouchi_vault_pwd
          chmod 600 /tmp/stouchi_vault_pwd

      - name: Run Ansible playbook
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventory.yml \
            -l stouchi-prod-server \
            -e "ansible_host=$VM_IP" \
            --vault-password-file /tmp/stouchi_vault_pwd \
            playbook.yml